name: Update repository Template

permissions:
  contents: write
  pull-requests: write
on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *" # Every 1 minute (for testing)

jobs:
  run:
    uses: ggsrc/public-ci/.github/workflows/cruft-update.yml@main
    secrets:
      CICD_DOCKER_BUILD_PAT: ${{ secrets.CICD_DOCKER_BUILD_PAT }}